### ISSUE TITLE
investigate google account authentication

### ISSUE THREAD

**Issue by jenniferjinyoungyang** [jenniferjinyoungyang/happybank#9]

**Comment by itsyurika** [comment]
https://blog.logrocket.com/guide-adding-google-login-react-app
https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid
https://www.npmjs.com/package/@react-oauth/google

**Comment by jenniferjinyoungyang** [comment]
https://blog.logrocket.com/guide-adding-google-login-react-app
https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid
https://www.npmjs.com/package/@react-oauth/google
